package br.ufrn.info.bpm.progressao;

public enum TarefaProgressao {
	ORGANIZAR_PEDIDO, EMITIR_PARECER_CHEFIA, EMITIR_PARECER_RELATOR, ASSINAR_PARECER;
	//SUBMETEU_PROCESSO, CHEFIA_EMITIU_PARECER, AVALIADOR_EMITIU_PARECER, PARECER_ASSINADO
}
