package br.ufrn.info.bpm.progressao;

public enum FiscalizacaoContratos {
	ENVIAR_MEMORANDO, PORTARIA, OCORRENCIA_SIPAC, PEDIR_PRONUNCIAMENTO,
	ENVIAR_INFO_FISCAL, OCORRENCIA, RECEBER_PRONUNCIAMENTO, TOMAR_PROVIDENCIAS;
}
